### ISSUE TITLE
Delete event button not being hidden when it should be

### ISSUE THREAD

**Issue by tirtow** [11foot8/RepresentsMe#139]
<img width="315" alt="Screen Shot 2019-04-16 at 12 26 31 PM" src="https://user-images.githubusercontent.com/14794963/56230939-e5249a00-6042-11e9-9468-33242d2cee55.png">

Should probably make the buttons into a `UIView` with a `UIButton` covering the entire view then the trash bin and "delete" buttons can be `UILabels` instead.

**Comment by bzsinger** [comment]
Partially addressed by @143
