### ISSUE TITLE
RSVPing through event details vc duplicates attendees

### ISSUE THREAD

**Issue by tirtow** [11foot8/RepresentsMe#141]
Currently creating a new `EventAttendee` every time the user clicks one of the RSVP buttons. Need to either:
- Store the `EventAttendee` and update it
  - Would need to pull the `EventAttendee` when the details view controller is loaded
- Delete the `EventAttendee` and then create a new one

Related to #126

**Comment by tirtow** [comment]
Upon further pondering, should probably store the `EventAttendee` since will need it to display the user's RSVP status for the `Event`

**Comment by bzsinger** [comment]
Addressed by #143
